select * from worker

SELECT UPPER(first_name) AS first_name
FROM worker;

SELECT DISTINCT DEPARTMENT
FROM Worker;

SELECT SUBSTRING(FIRST_NAME, 1, 3) AS FIRST_THREE_CHARS
FROM Worker;

SELECT POSITION('a' IN FIRST_NAME) AS POSITION_OF_A
FROM Worker
WHERE FIRST_NAME = 'Amitabh';

SELECT DISTINCT DEPARTMENT, LENGTH(DEPARTMENT) AS DEPARTMENT_LENGTH
FROM Worker;

SELECT *
FROM Worker
ORDER BY FIRST_NAME Asc, DEPARTMENT Desc;

SELECT *
FROM Worker
WHERE FIRST_NAME in ('Vipul', 'Satish');

SELECT *
FROM Worker
WHERE FIRST_NAME LIKE '%a%';

SELECT *
FROM Worker
WHERE FIRST_NAME LIKE '%h' AND LENGTH(FIRST_NAME) = 6;

SELECT *
FROM Worker
WHERE SALARY BETWEEN 100000 AND 500000;

SELECT *
FROM Worker
WHERE JOINING_DATE BETWEEN '2014-02-01' AND '2014-02-28';

SELECT COUNT(*)
from Worker
WHERE DEPARTMENT = 'Admin';

SELECT DEPARTMENT, COUNT(*) AS NUM_WORKERS
FROM Worker
GROUP BY DEPARTMENT
ORDER BY NUM_WORKERS DESC;

SELECT *
FROM Worker
WHERE WORKER_ID IN (
    SELECT WORKER_REF_ID
    FROM Title
    WHERE WORKER_TITLE = 'Manager'
    )
    
    SELECT FIRST_NAME, LAST_NAME, 
       (SELECT BONUS_AMOUNT 
        FROM Bonus 
        WHERE WORKER_REF_ID = Worker.WORKER_ID
        LIMIT 1) AS BONUS_AMOUNT
FROM Worker
WHERE WORKER_ID IN (
    SELECT WORKER_REF_ID
    FROM Bonus
);
    
    
    SELECT WORKER_REF_ID, WORKER_TITLE, AFFECTED_FROM, COUNT(*)
FROM Title
GROUP BY WORKER_REF_ID, WORKER_TITLE, AFFECTED_FROM
HAVING COUNT(*) > 1;


SELECT DISTINCT SALARY
FROM Worker
ORDER BY SALARY DESC
LIMIT 2;

SELECT MAX(SALARY) AS SecondHighestSalary
FROM Worker
WHERE SALARY < (SELECT MAX(SALARY) FROM Worker);

SELECT SALARY
FROM Worker
GROUP BY SALARY
HAVING COUNT(*) > 1;

SELECT FIRST_NAME, salary
FROM Worker
WHERE salary IN (
  SELECT salary
  FROM Worker
  GROUP BY salary
  HAVING COUNT(*) > 1
);

SELECT e.*
FROM Worker e
WHERE WORKER_ID <= (
  SELECT COUNT(*) / 2
  FROM Worker
  );
  
  SELECT department
FROM worker
GROUP BY department
HAVING COUNT(*) > 3;

SELECT * FROM worker WHERE WORKER_ID IN ((SELECT MIN(WORKER_ID) FROM worker), (SELECT MAX(WORKER_ID) FROM worker));

SELECT *
FROM worker
ORDER BY WORKER_ID DESC
LIMIT 5;

SELECT *
FROM Worker w1
WHERE SALARY = (
    SELECT MAX(SALARY)
    FROM Worker w2
    WHERE w1.DEPARTMENT = w2.DEPARTMENT
);

SELECT department, SUM(salary) AS total_salary
FROM worker
GROUP BY department;

SELECT FIRST_NAME,LAST_NAME
FROM worker
WHERE salary = (
  SELECT MAX(salary)
  FROM worker
);
